### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Ebaneck** [openMF/fineract-cn-containers#10]
This repo, unlike the other Mifos repositories, defines no style and contribution guidelines for submitting patches and additions.

Would love to submit a draft doc   :)

**Comment by israelzuniga** [comment]
@Ebaneck As far I know, This is a Mifos repo, so this will be the way:


1.  Sign up as a volunteer: https://mifos.org/take-action/volunteer
1. Join the communication channels: https://mifos.org/resources/community/communications/
1. Submit code

For Apache Fineract: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=103094318

**Comment by Ebaneck** [comment]
Thanks @israelzuniga
